# Generated by Django 6.0.2 on 2026-06-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_chat_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
